spring:
  application:
    name: devcollab-worker
  datasource:
    url: ${DEVCOLLAB_DB_URL:jdbc:postgresql://localhost:5432/devcollab}
    username: ${DEVCOLLAB_DB_USERNAME:devcollab}
    password: ${DEVCOLLAB_DB_PASSWORD:devcollab}
  kafka:
    bootstrap-servers: ${DEVCOLLAB_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${DEVCOLLAB_WORKER_KAFKA_GROUP_ID:devcollab-search-projection}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: record

server:
  port: ${DEVCOLLAB_WORKER_SERVER_PORT:8082}
  shutdown: graceful

devcollab:
  worker:
    kafka:
      topic: ${DEVCOLLAB_OUTBOX_KAFKA_TOPIC:devcollab.domain-events}
      dlq-topic: ${DEVCOLLAB_WORKER_KAFKA_DLQ_TOPIC:devcollab.domain-events.dlq}
      retry:
        interval: ${DEVCOLLAB_WORKER_KAFKA_RETRY_INTERVAL:PT1S}
        max-attempts: ${DEVCOLLAB_WORKER_KAFKA_RETRY_MAX_ATTEMPTS:2}
    search:
      group-id: ${DEVCOLLAB_WORKER_SEARCH_GROUP_ID:devcollab-search-projection}
    notification:
      enabled: ${DEVCOLLAB_WORKER_NOTIFICATION_ENABLED:true}
      group-id: ${DEVCOLLAB_WORKER_NOTIFICATION_GROUP_ID:devcollab-notification-projection}
  consumer-inbox:
    enabled: ${DEVCOLLAB_CONSUMER_INBOX_ENABLED:true}
  search:
    elasticsearch:
      enabled: ${DEVCOLLAB_ELASTICSEARCH_ENABLED:true}
      url: ${DEVCOLLAB_ELASTICSEARCH_URL:http://localhost:9200}
      index-name: ${DEVCOLLAB_ELASTICSEARCH_INDEX:devcollab-search}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: devcollab-worker
